services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=tax_engine'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_USER=user'
    ports:
      - '3308:3306'
